/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.micromanager.plugins.GaussianBlur;

/**
 *
 * @author BillBill
 */
import ij.process.AutoThresholder;
import java.text.NumberFormat;
import javax.swing.text.NumberFormatter;


import org.micromanager.PropertyMap;
import org.micromanager.PropertyMaps;
import org.micromanager.Studio;
import org.micromanager.data.ProcessorConfigurator;
import org.micromanager.internal.utils.MMFrame;

public class GaussianBlurConfigurator extends MMFrame implements ProcessorConfigurator {

    private final Studio studio_;
    private final PropertyMap settings_;
    /**
     * Creates new form GaussianBlurConfigurator
     */
    public GaussianBlurConfigurator(PropertyMap settings, Studio studio) {
      studio_ = studio;
      settings_ = settings;
      initComponents();
      loadSettingValue();
      for(int i=0; i<AutoThresholder.getMethods().length; i++)
        jComboBox_ThreMethod.addItem(AutoThresholder.getMethods()[i]);
      jComboBox_ThreMethod.setSelectedIndex(0);
      super.loadAndRestorePosition(200, 200);
      
   }
   private void loadSettingValue() {
      // jSpinner_Radius.setValue(settings_.getDouble(GaussianBlurPlugin.PROCESSOR_RadiusKey, GaussianBlurPlugin.PROCESSOR_Radius));
      
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Radius = new javax.swing.JLabel();
        jSpinner_Radius = new javax.swing.JSpinner();
        jLabel_ThreMethod = new javax.swing.JLabel();
        jComboBox_ThreMethod = new javax.swing.JComboBox<>();

        jPanel1.setName("Test Panel"); // NOI18N

        jLabel_Radius.setText("Radius");

        jSpinner_Radius.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 100.0d, 0.1d));
        jSpinner_Radius.setInheritsPopupMenu(true);
        jSpinner_Radius.setName(""); // NOI18N
        jSpinner_Radius.setValue(2.000);

        jLabel_ThreMethod.setText("Thres Method");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_ThreMethod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_ThreMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Radius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner_Radius, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Radius)
                    .addComponent(jSpinner_Radius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ThreMethod)
                    .addComponent(jComboBox_ThreMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_ThreMethod;
    private javax.swing.JLabel jLabel_Radius;
    private javax.swing.JLabel jLabel_ThreMethod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner_Radius;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showGUI() {
        pack();
        setVisible(true);
    }

    @Override
    public void cleanup() {
        dispose();        
    }

    @Override
    public PropertyMap getSettings() {
       // Save preferences now.       
     studio_.profile().getSettings(GaussianBlurConfigurator.class).
                putDouble(GaussianBlurPlugin.PROCESSOR_RadiusKey, GaussianBlurPlugin.PROCESSOR_Radius);
     studio_.profile().getSettings(GaussianBlurConfigurator.class).
                putInteger(GaussianBlurPlugin.PROCESSOR_AutoTresholdKey, GaussianBlurPlugin.PROCESSOR_AutoThreshold);
      PropertyMap.Builder builder = PropertyMaps.builder();
      builder.putDouble(GaussianBlurPlugin.PROCESSOR_RadiusKey, (double) jSpinner_Radius.getValue());      
      builder.putInteger(GaussianBlurPlugin.PROCESSOR_AutoTresholdKey, jComboBox_ThreMethod.getSelectedIndex());
      return builder.build();
    }
}
